---
title: "Blur_RT_"
author: "Jason Geller"
date: "1/5/2022"
output: html_document
---
# This markdown file shows how to read data abd plot our accuracy, RT, and memory data for our ploit study. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(tidyverse)
library(here)
library(data.table)
library(ggrepel)
library(osfr)

```
# OSF Data

First let's read in our data from OSF



```{r}
#usethis::edit_r_environ()need to allow osf to gain access use code below
#OSF_PAT = "rnuJPLnoikl36gDSaxuGfWUD8IgaI2e7UAYix0CIiFpelwafTS4ww8v6Yj5j9DUv5hpy8r"
#osf_auth("rnuJPLnoikl36gDSaxuGfWUD8IgaI2e7UAYix0CIiFpelwafTS4ww8v6Yj5j9DUv5hpy8r")

osf_retrieve_file("https://osf.io/8bgyn/") %>%
    osf_download(conflicts = "skip")

dataset<-read_csv("rts_pilot_010821.csv")


```

```{r message=FALSE, warning=FALSE, echo=FALSE} 
# read in low test expect data exported from gorilla
#setwd(here::here('Expt2_low_high', "mturk_cue_recall_low")) # folder to find Ps in

#data=here::here("Expt2_low_high", "mturk_cue_recall_low")  # path to data files

data=here::here("data")

file_list_rts=list.files(data, pattern=".csv") # list of data files

setwd(data)
# read in all files
rts <-
  do.call("rbind.fill", lapply(file_list_rts, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
    fread(files, header=TRUE, sep=",", na.strings = "", fill=TRUE)}))#fread makes reading in f


#collect RTs
dataset <- rts %>% 
  dplyr::filter(maintrials.thisRepN==0) %>%
  dplyr::select(participant, date, string, study, blur, rt, corr, lex, key_resp_2.keys)%>%
  mutate(lex=ifelse(lex=="y", "m", ifelse(lex=="n", "z", lex)), corr=ifelse(lex==key_resp_2.keys, 1, 0)) %>%
   drop_na()
```

```{r}

top_mean <-dataset %>%  #get means for plot
  dplyr::filter(lex=="m")%>%
   dplyr::group_by(blur)%>%
   dplyr::summarise(mean1=mean(corr)) %>%
  dplyr::ungroup()


p_mean <-dataset %>%  #get means for plot
  dplyr::filter(lex=="m")%>%
    dplyr::group_by(participant, blur)%>%
     dplyr::summarise(mean1=mean(corr))
      


```
```{r}
p_mean <-dataset %>%  #get means for plot
  dplyr::filter(lex=="m")%>%
    dplyr::group_by(participant, blur)%>%
     dplyr::summarise(mean1=mean(corr))


```




```{r prep, message=FALSE}
## packages
library(tidyverse)
library(colorspace)
library(ragg)
library(cowplot)
library(ggtext)
library(pdftools)

bold <- element_text(face = "bold", color = "black", size = 16) #axis bold


theme_set(theme_minimal(base_size = 15, base_family = "Arial"))
theme_update(
  panel.grid.major = element_line(color = "grey92", size = .4),
  panel.grid.minor = element_blank(),
  axis.title.x = element_text(color = "grey30", margin = margin(t = 7)),
  axis.title.y = element_text(color = "grey30", margin = margin(r = 7)),
  axis.text = element_text(color = "grey50"),
  axis.ticks =  element_line(color = "grey92", size = .4),
  axis.ticks.length = unit(.6, "lines"),
  legend.position = "top",
  plot.title = element_text(hjust = 0, color = "black", 
                            family = "Arial",
                            size = 21, margin = margin(t = 10, b = 35)),
  plot.subtitle = element_text(hjust = 0, face = "bold", color = "grey30",
                               family = "Arial", 
                               size = 14, margin = margin(0, 0, 25, 0)),
  plot.title.position = "plot",
  plot.caption = element_text(color = "grey50", size = 10, hjust = 1,
                              family = "Arial", 
                              lineheight = 1.05, margin = margin(30, 0, 0, 0)),
  plot.caption.position = "plot", 
  plot.margin = margin(rep(20, 4))
)
pal <- c("#FF8C00", "#A034F0", "#159090")
```


```{r}
p3 <- ggplot(p_mean, aes(x = blur , y = mean1, fill = blur)) +
    coord_cartesian(ylim = c(.7,1)) + 
  
  ggdist::stat_halfeye(
    aes(
      y = mean1,
      color = blur,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
    geom_point(aes(x = blur, y = mean1, colour = blur),position = position_jitter(width = .05), size = 1, shape = 20)+
    geom_boxplot(aes(x = blur, y = mean1, fill = blur),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  labs(subtitle = "Word Accuracy")+
     scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") + 
    stat_summary(fun=mean, geom="point", colour="darkred", size=3)+
    labs(y = "Accuracy", x = "Blur") + theme_bw(base_size = 14)+
    geom_label_repel(data=top_mean, aes(y=mean1, label=round(mean1, 2)), color="black", min.segment.length = 0, seed = 42, box.padding = 0.5) + 
    theme(axis.text=bold) + theme(legend.position = "none") 
  #  ggsave('place.png', width = 8, height = 6)

p3
```
# Delta


```{r}
#Delta plots (one per subject)

quibble <- function(x, q = seq(.1, .9, .2)) {
  tibble(x = quantile(x, q), q = q)
}


dataset %>%
  group_by(participant, lex, blur,corr) %>%
  summarise(RT = list(quibble(rt, seq(.1, .9, .2)))) %>% 
  tidyr::unnest(RT) -> data.quantiles


data.delta <- data.quantiles %>%
  dplyr::filter(corr==1) %>%
  dplyr::select(-corr) %>%
  dplyr::group_by(participant, lex,blur, q) %>%
  dplyr::summarize(RT=mean(x),
            Delta=base::diff(x)) 


delta<- data.delta %>%
ggplot(aes(y=Delta, x=RT, color=blur)) +
  geom_line(alpha=.3, aes(group=participant), size=1.2)+
  facet_wrap(~lex)

delta
  
```
```{r}
#Delta plots (based on vincentiles)
data.quantiles %>%
  filter(corr==1, lex=="m") %>%
  select(-corr) %>%
  group_by(lex,blur,q) %>%
  summarize(RT=mean(x)) ->vincentiles

vincentiles %>%
  dplyr::group_by(blur,q) %>%
  dplyr::summarise(MRT=mean(RT)),
            Delta=diff(RT)) %>%
ggplot(aes(y=Delta, x=MRT)) +
  geom_line()+
  geom_point()+
  facet_wrap(~blur) +
  ylim(0, 10)

```

```{r}

p_mean <- dataset %>%  #get means for plot
  dplyr::filter(lex=="m") %>%
    dplyr::group_by(participant, blur)%>%
     dplyr::summarise(mean1=mean(corr))
      
top_mean <- p_mean  %>% 
  dplyr::group_by(blur)%>%
    dplyr::summarise(mean1=mean(mean1)) %>%
   dplyr::ungroup()


```

```{r}
p4 <- ggplot(p_mean, aes(x = blur , y = mean1, fill = blur)) +
    coord_cartesian(ylim = c(.5,1)) + 
  
  ggdist::stat_halfeye(
    aes(
      y = mean1,
      color = blur,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
    geom_point(aes(x = blur, y = mean1, colour = blur),position = position_jitter(width = .10), size = 1, shape = 20)+
    geom_boxplot(aes(x = blur, y = mean1, fill = blur),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  labs(subtitle = "Word Accuracy")+
     scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") + 
    stat_summary(fun="mean", geom="point", colour="darkred", size=3)+
    labs(y = "Accuracy", x = "Blur") + theme_bw(base_size = 14)+
    geom_label_repel(data=top_mean, aes(y=mean1, label=round(mean1, 2)), color="black", min.segment.length = 0, seed = 42, box.padding = 0.5) + 
    theme(axis.text=bold) + theme(legend.position = "none") 
  #  ggsave('place.png', width = 8, height = 6)

p4
```
```{r}

p_mean <- dataset %>%  #get means for plot
  dplyr::filter(lex=="z") %>%
    dplyr::group_by(date, blur)%>%
     dplyr::summarise(mean1=mean(corr))
      
top_mean <- p_mean  %>% dplyr::group_by(blur)%>%
    dplyr::summarise(mean1=mean(mean1)) %>%
   dplyr::ungroup()


```

```{r}
p5 <- ggplot(p_mean, aes(x = blur , y = mean1, fill = blur)) +
    coord_cartesian(ylim = c(.5,1)) + 
  
  ggdist::stat_halfeye(
    aes(
      y = mean1,
      color = blur,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
    geom_point(aes(x = blur, y = mean1, colour = blur),position = position_jitter(width = .10), size = 1, shape = 20)+
    geom_boxplot(aes(x = blur, y = mean1, fill = blur),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  labs(subtitle = "Nonword Accuracy")+
     scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") + 
    stat_summary(fun="mean", geom="point", colour="darkred", size=3)+
    labs(y = "Accuracy", x = "Blur") + theme_bw(base_size = 14)+
    geom_label_repel(data=top_mean, aes(y=mean1, label=round(mean1, 2)), color="black", min.segment.length = 0, seed = 42, box.padding = 0.5) + 
    theme(axis.text=bold) + theme(legend.position = "none") 
  #  ggsave('place.png', width = 8, height = 6)

p5
```


```{r}

p_mean <- dataset %>%  #get means for plot
  dplyr::filter(lex=="m") %>%
    dplyr::group_by(date, blur)%>%
     dplyr::summarise(mean1=mean(rt))
      
top_mean <- p_mean  %>% dplyr::group_by(blur)%>%
    dplyr::summarise(mean1=mean(mean1)) %>%
   dplyr::ungroup()
      


```

# Memory

Because we have key presses and clicks we need to split and combine 

# Conditionalzed on recognizing words during encoding 

```


```

```{r}


#collect RTs for keypress
dataset_m_rts <- rts %>% 
  dplyr::filter(maintrials.thisRepN==0) %>%
  dplyr::select(participant, date, string, study, blur, rt, corr, lex, key_resp_2.keys)%>%
  mutate(encode_lex=ifelse(lex=="y", "m", ifelse(lex=="n", "z", lex)), study=ifelse(study=="old", "m", study), lex_corr=ifelse(encode_lex==key_resp_2.keys, 1, 0)) %>%
  rename("response"= "key_resp_2.keys")%>%
  filter(encode_lex=="m")%>%
  select(-corr, -lex)%>%
   drop_na()

#collect rts for button presses
dataset_m_clicks <- rts %>% 
  dplyr::filter(maintrials.thisRepN==0) %>%
  dplyr::select(participant, date, string, study, blur, rt, corr, lex, targ_click.clicked_name)%>%
  mutate(clicked=ifelse(targ_click.clicked_name=="button_right_main","m", "z"), encode_lex=ifelse(lex=="y", "m", ifelse(lex=="n", "z", lex)), study=ifelse(study=="old", "m", study), lex_corr=ifelse(encode_lex==clicked, 1, 0)) %>%
  dplyr::filter(encode_lex=="m")%>%
  select(-corr, -lex, -clicked)%>%
  rename("response"= "targ_click.clicked_name") %>%
  na.omit(.)

#bind responses
dataset_rts<-rbind(dataset_m_rts, dataset_m_clicks)

#get study responses for rts
dataset_mem_key <- rts %>% 
  dplyr::filter(test_phase.thisRepN==0) %>%
  dplyr::select(participant, date, study, string, blur, rt, corr, lex, key_resp_3.keys)%>%
  mutate(study=ifelse(study=="old", "m", ifelse(study=="new", "z", study)))%>%
  rename("sayold"="key_resp_3.keys") %>%
  drop_na() 
#get study responses for button presses

dataset_mem_click <- rts %>% 
  dplyr::filter(test_phase.thisRepN==0) %>%
  dplyr::select(participant, date, study, string, blur, rt, corr, lex, test_click.clicked_name)%>%
  rename("sayold"="test_click.clicked_name") %>%
  mutate(study=ifelse(study=="old", "m", ifelse(study=="new", "z", study)))%>%
  mutate(sayold=ifelse(sayold=="button_right_test","m", "z")) %>%
  drop_na()
# Ps took experiment more than once
bad_p=c("200254", "200254")
# bind the memory responses 
dataset_mem<-rbind(dataset_mem_key, dataset_mem_click)
# get rid of bad Ps
dataset_mem_new<- dataset_mem %>% filter(participant != bad_p)
#get the old stims
old<-dataset_mem_new  %>%
  filter(study=="m") # get old

#bind old accuracy with studied items and get rid of items not successfully identified at study

rt_study_old<-dataset_rts %>% select(participant, study, date, string, blur, lex_corr) %>%
  dplyr::rename("corr_rt" = "lex_corr")%>%
  left_join(old,., by=c("participant", "study", "string", "date", "blur"))  %>% # get words at encoding and merge %>% 
  mutate(cond=ifelse(corr_rt==0, 1, 0), )%>%
  filter(cond!=1) %>%
  select(-corr_rt, -cond)

# get new items 

new= dataset_mem %>%
  filter(study=="z")


# merge old and new items together

old_new=rbind(rt_study_old,new)


```


# dprime

```{r}

#response as character
#calculate hit rate and far and compute dprime and other measures
ex4=old_new %>% 
  dplyr::mutate(condition1= dplyr::case_when(
blur == "C"~ "Clear",
blur =="HB" ~ "High Blur",
TRUE ~ "Low Blur"), 
isold= dplyr::case_when (
study== "m" | study=="old" ~ 1,
study== "z" | study=="new" ~ 0),
sayold=dplyr::case_when(
sayold=="m"~ 1,
sayold=="z" ~ 0,
))
#classic SDT
sdt <- ex4 %>%
dplyr::mutate(type = "hit",
type = ifelse(isold==1 & sayold==0, "miss", type),
type = ifelse(isold==0 & sayold==0, "cr", type), # Correct rejection
type = ifelse(isold==0 & sayold==1, "fa", type))



sdt1 <- sdt %>% 
  dplyr::group_by(participant, type,blur) %>% 
  dplyr::summarise(count = n()) %>% 
  tidyr::spread(type, count)  # Format data to one row per person

sdt2 <- sdt1 %>%
dplyr::group_by(participant, blur)%>%
dplyr::mutate(hr = hit / (hit+miss),
fa = fa / (fa+cr)) %>%
dplyr::mutate(hr=case_when(
is.na(hr) ~ 0.99,
TRUE ~ hr),
fa=case_when(
is.na(fa) ~ 0.01,
TRUE ~ fa),
zhr=qnorm(hr),
zfa=qnorm(fa),
dprime = zhr-zfa) %>%
ungroup()
  

```
```{r}
# plot HR and FAR
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
sdt1=sdt2  %>% select(participant, blur, hr, fa) %>% 
  pivot_longer(hr:fa, names_to="type") %>%
  dplyr::mutate(isold=case_when(type=="hr" ~ "Old", type=="fa" ~ "New"))

sdt1$isold<-factor(sdt1$isold, levels=c("Old", "New"))

sdt1$Condition<-factor(sdt1$blur, levels=c("C", "LB", "HB"))


fig1b <- ggplot(sdt1,aes(x=Condition,y=value,fill=Condition))+ facet_grid(~isold) + 
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .4,adjust=4)+
  geom_point(position=position_jitter(width = .15),size = 1, alpha = 0.2) + 
  geom_boxplot(aes(x = Condition, y = value),outlier.shape = NA,
               alpha = 0.3, width = .1, colour = "BLACK") +
    stat_summary(fun=mean, geom="point", colour="darkred", size=5)+
  theme_cowplot() +
  scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") +
  labs(y = "Pr Saying Old", x = "Typeface") + theme(legend.position = "none")


fig1b


```

```{r}
# Plot drime
theme_set(theme_minimal(base_size = 16, base_family = "Arial"))

dprime=sdt2  %>% select(participant, blur, dprime)



# get withinsubject CIs
sfgend_wsci= Rmisc::summarySEwithin(data = dprime, measurevar = "dprime",
                       withinvars = "blur",idvar = "participant")
#plot

fig1a <- ggplot(dprime,aes(x=blur,y=dprime,fill=blur))+
  #geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .4,adjust=4)+
  geom_point(position=position_jitter(width = .15),size = 1, alpha = 0.2) + 
  geom_boxplot(aes(x = blur, y = dprime),outlier.shape = NA,
               alpha = 0.3, width = .1, colour = "BLACK") +
    geom_line(data=sfgend_wsci,aes(y=dprime, group=1), size=1)+ 
  #stat_summary(fun="mean", geom="point", colour="darkred", size=3) + 
    geom_pointrange(data=sfgend_wsci, aes(y=dprime, ymin=dprime, ymax=dprime), size=.8, color="darkred")+
  theme_cowplot() +
  scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") +
  labs(y = "Sensitivity(d')", x = "Typeface") + theme(legend.position = "none") + 
    geom_label_repel(data=sfgend_wsci, aes(y=dprime, label=round(dprime, 2)), min.segment.length = 0, seed = 42, box.padding = 0.5)


fig1a
```
```{r prep, message=FALSE}
## packages
library(tidyverse)
library(colorspace)
library(ragg)
library(cowplot)
library(ggtext)
library(pdftools)
theme_set(theme_minimal(base_size = 15, base_family = "Neutraface Slab Display TT Bold"))
theme_update(
  panel.grid.major = element_line(color = "grey92", size = .4),
  panel.grid.minor = element_blank(),
  axis.title.x = element_text(color = "grey30", margin = margin(t = 7)),
  axis.title.y = element_text(color = "grey30", margin = margin(r = 7)),
  axis.text = element_text(color = "grey50"),
  axis.ticks =  element_line(color = "grey92", size = .4),
  axis.ticks.length = unit(.6, "lines"),
  legend.position = "top",
  plot.title = element_text(hjust = 0, color = "black", 
                            family = "Neutraface 2 Display Titling",
                            size = 21, margin = margin(t = 10, b = 35)),
  plot.subtitle = element_text(hjust = 0, face = "bold", color = "grey30",
                               family = "Neutraface Text Book Italic", 
                               size = 14, margin = margin(0, 0, 25, 0)),
  plot.title.position = "plot",
  plot.caption = element_text(color = "grey50", size = 10, hjust = 1,
                              family = "Neutraface Display Medium", 
                              lineheight = 1.05, margin = margin(30, 0, 0, 0)),
  plot.caption.position = "plot", 
  plot.margin = margin(rep(20, 4))
)
pal <- c("#FF8C00", "#A034F0", "#159090")
```
```{r}

## flat violinplots
### It relies largely on code previously written by David Robinson 
### (https://gist.github.com/dgrtwo/eb7750e74997891d7c20) and ggplot2 by H Wickham


#check if required packages are installed
packages <- c("cowplot", "readr", "ggplot2" , "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}

#Load packages
library(ggplot2)
library(dplyr)
library(lavaan)

# Defining the geom_flat_violin function. Note: the below code modifies the 
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}


# horizontal nudge position adjustment
# copied from https://github.com/tidyverse/ggplot2/issues/2733
position_hnudge <- function(x = 0) {
  ggproto(NULL, PositionHNudge, x = x)
}


PositionHNudge <- ggproto("PositionHNudge", Position,
                          x = 0,
                          required_aes = "x",
                          setup_params = function(self, data) {
                            list(x = self$x)
                          },
                          compute_layer = function(data, params, panel) {
                            transform_position(data, function(x) x + params$x)
                          }
)
```



```{r}
top_mean <-dprime %>%  #get means for plot
   dplyr::group_by(blur)%>%
   dplyr::summarise(mean1=mean(dprime))


p_mean <-dprime %>%  #get means for plot
    dplyr::group_by(participant, blur)%>%
     dplyr::summarise(mean1=mean(dprime))
      
# get withinsubject CIs
sfgend_wsci= Rmisc::summarySEwithin(data = dprime, measurevar = "dprime",
                       withinvars = "blur",idvar = "participant")

bold <- element_text(face = "bold", color = "black", size = 14) #axis bold
                                                
p3 <- ggplot(p_mean, aes(x =blur, y = mean1, fill = blur)) + 
    coord_cartesian(ylim = c(0,4.5)) + 
  
  ggdist::stat_halfeye(
    aes(
      y = mean1,
      color = blur,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  ) +
    geom_point(aes(x = blur, y = mean1, colour = blur),position = position_jitter(width = .10), size = 1, shape = 20)+
    geom_boxplot(aes(x = blur, y = mean1, fill = blur),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  labs(
    subtitle = "Sensitivity by Level of Blurring",
    caption = 'Simialr to other studies using blurring we see HB words are better remembered than Clear words. We do not see a difference')+
     scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") + 
   # stat_summary(fun="mean", geom="point", colour="darkred", size=3)+
      geom_pointrange(data=sfgend_wsci, aes(y=dprime, ymin=dprime-ci, ymax=dprime+ci), size=.7, color="black", position = position_hnudge(x = 0.1))+
   #stat_summary(fun="mean_cl_normal", geom="errorbar", colour="darkred", size=3)+
    labs(y = "D prime", x = "Blur Condition") + theme_bw(base_size = 16)+
    geom_label_repel(data=top_mean, aes(y=mean1, label=round(mean1, 2)), color="black", min.segment.length = 0, seed = 42, box.padding = 0.5, position = position_hnudge(x = 0.1)) + 
    theme(axis.text=bold) + theme(legend.position = "none") 
  #  ggsave('place.png', width = 8, height = 6)

p3


ggsave(here::here("figures", "dprime.pdf"), 
       width = 13, height = 8, device = cairo_pdf)

```



```{r}
hrate<-sdt %>% select(participant, hr, blur)


# get withinsubject CIs
sfgend_wsci= Rmisc::summarySEwithin(data = hrate, measurevar = "hr",
                       withinvars = "blur",idvar = "participant")
#plot

fig1a <- ggplot(hrate,aes(x=blur,y=hr,fill=blur))+
  #geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .4,adjust=4)+
  geom_point(position=position_jitter(width = .15),size = 1, alpha = 0.2) + 
  geom_boxplot(aes(x = blur, y = hr),outlier.shape = NA,
               alpha = 0.3, width = .1, colour = "BLACK") +
    geom_line(data=sfgend_wsci,aes(y=hr, group=1), size=1)+ 
  #stat_summary(fun="mean", geom="point", colour="darkred", size=3) + 
    geom_pointrange(data=sfgend_wsci, aes(y=hr, ymin=hr, ymax=hr), size=.5, color="darkred")+
  theme_cowplot() +
  scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2") +
  labs(y = "Hit rate", x = "Typeface") + theme(legend.position = "none") + 
    geom_label_repel(data=sfgend_wsci, aes(y=hr, label=round(hr, 2)), min.segment.length = 0, seed = 42, box.padding = 0.5)


fig1a

```



```{r}
library(afex)#ANOVA
library(report)#report ANOVA results
library(emmeans)#postdoc
a1 <- aov_ez("participant", "dprime", sdt,within=c("blur")) # mixed
summary(a1)

```


```{r session}
Sys.time()
sessionInfo()
```


